// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'contact.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Contact _$$_ContactFromJson(Map<String, dynamic> json) => _$_Contact(
      jid: json['jid'] as String,
      node: json['node'] as String?,
      displayName: json['display_name'] as String,
      shortName: json['short_name'] as String,
      contactEmail: json['contact_email'] as String,
      contactPhone: json['contact_phone'] as String,
      icons: IconData.fromJson(json['icons'] as Map<String, dynamic>),
      gentime: json['gentime'] as int,
      role: json['role'] as String,
      mood: json['mood'] as String?,
      teamStatus: json['status'] as String,
      lastActivity: json['last_activity'] == null ? null : DateTime.parse(json['last_activity'] as String),
      isArchive: json['is_archive'] as bool? ?? false,
      botname: json['botname'] as String?,
      sections: (json['sections'] as List<dynamic>).map((e) => e as String).toList(),
      canSendMessage: json['can_send_message'] as bool? ?? false,
      cantSendMessageReason: json['cant_send_message_reason'] as String?,
      canCall: json['can_call'] as bool? ?? false,
      canCreateTask: json['can_create_task'] as bool? ?? false,
      canImportTasks: json['can_import_tasks'] as bool? ?? false,
      canAddToGroup: json['can_add_to_group'] as bool? ?? false,
      canDelete: json['can_delete'] as bool? ?? false,
      changeableFields: (json['changeable_fields'] as List<dynamic>?)?.map((e) => e as String).toList(),
      familyName: json['family_name'] as String?,
      givenName: json['given_name'] as String?,
      patronymic: json['patronymic'] as String?,
      defaultLang: json['default_lang'] as String?,
      debugShowActivity: json['debug_show_activity'] as bool? ?? false,
      dropallEnabled: json['dropall_enabled'] as bool? ?? false,
      altSend: json['alt_send'] as bool? ?? false,
      asteriskMention: json['asterisk_mention'] as bool? ?? false,
      alwaysSendPushes: json['always_send_pushes'] as bool? ?? false,
      hidePushesContent: json['hide_pushes_content'] as bool? ?? false,
      timezone: json['timezone'] as String?,
      quietTimeStart: json['quiet_time_start'] as String?,
      quietTimeFinish: json['quiet_time_finish'] as String?,
      focusUntil: json['focus_until'] == null ? null : DateTime.parse(json['focus_until'] as String),
      groupNotificationsEnabled: json['group_notifications_enabled'] as bool? ?? false,
      taskNotificationsEnabled: json['task_notifications_enabled'] as bool? ?? false,
      contactShortView: json['contact_short_view'] as bool? ?? false,
      groupShortView: json['group_short_view'] as bool? ?? false,
      taskShortView: json['task_short_view'] as bool? ?? false,
      contactMshortView: json['contact_mshort_view'] as bool? ?? false,
      groupMshortView: json['group_mshort_view'] as bool? ?? false,
      auth2faEnabled: json['auth_2fa_enabled'] as bool? ?? false,
      auth2faStatus: json['auth_2fa_status'] as String?,
      taskMshortView: json['task_mshort_view'] as bool? ?? false,
      contactShowArchived: json['contact_show_archived'] as bool? ?? false,
      unreadFirst: json['unread_first'] as bool? ?? false,
      mUnreadFirst: json['munread_first'] as bool? ?? false,
      canAddToTeam: json['can_add_to_team'] as bool? ?? false,
      canManageSections: json['can_manage_sections'] as bool? ?? false,
      canManageProjects: json['can_manage_projects'] as bool? ?? false,
      canManageTags: json['can_manage_tags'] as bool? ?? false,
      canManageIntegrations: json['can_manage_integrations'] as bool? ?? false,
      canManageColorRules: json['can_manage_color_rules'] as bool? ?? false,
      canCreateGroup: json['can_create_group'] as bool? ?? false,
      canJoinPublicGroups: json['can_join_public_groups'] as bool? ?? false,
      canJoinPublicTasks: json['can_join_public_tasks'] as bool? ?? false,
      customFields: json['custom_fields'] == null
          ? null
          : ContactCustomFields.fromJson(json['custom_fields'] as Map<String, dynamic>),
      canDeleteAnyMessage: json['can_delete_any_message'] as bool? ?? false,
    );

Map<String, dynamic> _$$_ContactToJson(_$_Contact instance) => <String, dynamic>{
      'jid': instance.jid,
      'node': instance.node,
      'display_name': instance.displayName,
      'short_name': instance.shortName,
      'contact_email': instance.contactEmail,
      'contact_phone': instance.contactPhone,
      'icons': instance.icons.toJson(),
      'gentime': instance.gentime,
      'role': instance.role,
      'mood': instance.mood,
      'status': instance.teamStatus,
      'last_activity': instance.lastActivity?.toIso8601String(),
      'is_archive': instance.isArchive,
      'botname': instance.botname,
      'sections': instance.sections,
      'can_send_message': instance.canSendMessage,
      'cant_send_message_reason': instance.cantSendMessageReason,
      'can_call': instance.canCall,
      'can_create_task': instance.canCreateTask,
      'can_import_tasks': instance.canImportTasks,
      'can_add_to_group': instance.canAddToGroup,
      'can_delete': instance.canDelete,
      'changeable_fields': instance.changeableFields,
      'family_name': instance.familyName,
      'given_name': instance.givenName,
      'patronymic': instance.patronymic,
      'default_lang': instance.defaultLang,
      'debug_show_activity': instance.debugShowActivity,
      'dropall_enabled': instance.dropallEnabled,
      'alt_send': instance.altSend,
      'asterisk_mention': instance.asteriskMention,
      'always_send_pushes': instance.alwaysSendPushes,
      'hide_pushes_content': instance.hidePushesContent,
      'timezone': instance.timezone,
      'quiet_time_start': instance.quietTimeStart,
      'quiet_time_finish': instance.quietTimeFinish,
      'focus_until': instance.focusUntil?.toIso8601String(),
      'group_notifications_enabled': instance.groupNotificationsEnabled,
      'task_notifications_enabled': instance.taskNotificationsEnabled,
      'contact_short_view': instance.contactShortView,
      'group_short_view': instance.groupShortView,
      'task_short_view': instance.taskShortView,
      'contact_mshort_view': instance.contactMshortView,
      'group_mshort_view': instance.groupMshortView,
      'auth_2fa_enabled': instance.auth2faEnabled,
      'auth_2fa_status': instance.auth2faStatus,
      'task_mshort_view': instance.taskMshortView,
      'contact_show_archived': instance.contactShowArchived,
      'unread_first': instance.unreadFirst,
      'munread_first': instance.mUnreadFirst,
      'can_add_to_team': instance.canAddToTeam,
      'can_manage_sections': instance.canManageSections,
      'can_manage_projects': instance.canManageProjects,
      'can_manage_tags': instance.canManageTags,
      'can_manage_integrations': instance.canManageIntegrations,
      'can_manage_color_rules': instance.canManageColorRules,
      'can_create_group': instance.canCreateGroup,
      'can_join_public_groups': instance.canJoinPublicGroups,
      'can_join_public_tasks': instance.canJoinPublicTasks,
      'custom_fields': instance.customFields?.toJson(),
      'can_delete_any_message': instance.canDeleteAnyMessage,
    };
