// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'contact.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Contact _$$_ContactFromJson(Map<String, dynamic> json) => _$_Contact(
      userUid: json['user_uid'] as String?,
      phone: json['phone'] as String,
      contactPhone: json['contact_phone'] as String,
      contactEmail: json['contact_email'] as String,
      familyName: json['family_name'] as String,
      givenName: json['given_name'] as String,
      patronymic: json['patronymic'] as String,
      role: json['role'] as String,
      mood: json['mood'] as String,
      debugShowActivity: json['debug_show_activity'] as bool,
      status: json['status'] as String,
      sections: (json['sections'] as List<dynamic>).map((e) => e as String).toList(),
      altSend: json['alt_send'] as bool,
      focusUntil: const DateTimeConverter().fromJson(json['focus_until'] as String),
      asteriskMention: json['asterisk_mention'] as bool,
      alwaysSendPushes: json['always_send_pushes'] as bool,
      hidePushesContent: json['hide_pushes_content'] as bool,
      unreadFirst: json['unread_first'] as bool,
      munreadFirst: json['munread_first'] as bool,
      defaultLang: json['default_lang'] as String,
      timezone: json['timezone'] as String,
      quietTimeStart: json['quiet_time_start'] as String,
      quietTimeFinish: json['quiet_time_finish'] as String,
      groupNotificationsEnabled: json['group_notifications_enabled'] as bool,
      taskNotificationsEnabled: json['task_notifications_enabled'] as bool,
      contactShortView: json['contact_short_view'] as bool,
      groupShortView: json['group_short_view'] as bool,
      taskShortView: json['task_short_view'] as bool,
      meetingShortView: json['meeting_short_view'] as bool,
      contactMshortView: json['contact_mshort_view'] as bool,
      contactShowArchived: json['contact_show_archived'] as bool,
      groupMshortView: json['group_mshort_view'] as bool,
      taskMshortView: json['task_mshort_view'] as bool,
      meetingMshortView: json['meeting_mshort_view'] as bool,
    );

Map<String, dynamic> _$$_ContactToJson(_$_Contact instance) => <String, dynamic>{
      'user_uid': instance.userUid,
      'phone': instance.phone,
      'contact_phone': instance.contactPhone,
      'contact_email': instance.contactEmail,
      'family_name': instance.familyName,
      'given_name': instance.givenName,
      'patronymic': instance.patronymic,
      'role': instance.role,
      'mood': instance.mood,
      'debug_show_activity': instance.debugShowActivity,
      'status': instance.status,
      'sections': instance.sections,
      'alt_send': instance.altSend,
      'focus_until': const DateTimeConverter().toJson(instance.focusUntil),
      'asterisk_mention': instance.asteriskMention,
      'always_send_pushes': instance.alwaysSendPushes,
      'hide_pushes_content': instance.hidePushesContent,
      'unread_first': instance.unreadFirst,
      'munread_first': instance.munreadFirst,
      'default_lang': instance.defaultLang,
      'timezone': instance.timezone,
      'quiet_time_start': instance.quietTimeStart,
      'quiet_time_finish': instance.quietTimeFinish,
      'group_notifications_enabled': instance.groupNotificationsEnabled,
      'task_notifications_enabled': instance.taskNotificationsEnabled,
      'contact_short_view': instance.contactShortView,
      'group_short_view': instance.groupShortView,
      'task_short_view': instance.taskShortView,
      'meeting_short_view': instance.meetingShortView,
      'contact_mshort_view': instance.contactMshortView,
      'contact_show_archived': instance.contactShowArchived,
      'group_mshort_view': instance.groupMshortView,
      'task_mshort_view': instance.taskMshortView,
      'meeting_mshort_view': instance.meetingMshortView,
    };
