targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.

          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          ignore_unannotated: false
          include_if_null: true
          nullable: true
          field_rename: none
          generic_argument_factories: false

          # If true, generated toJson methods will explicitly call toJson on nested objects.
          explicit_to_json: true

