name: tdproto_dart
description: Tada types example.
version: 0.0.1
author: Tada
homepage: tada.team

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.1
  supercharged: ^1.11.1
  dart_extensions: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.6
  freezed: ^0.12.3
  json_serializable: ^3.5.0
  test: ^1.15.7
