// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target

part of 'push_device.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more informations: https://github.com/rrousselGit/freezed#custom-getters-and-methods');

PushDevice _$PushDeviceFromJson(Map<String, dynamic> json) {
  return _PushDevice.fromJson(json);
}

/// @nodoc
class _$PushDeviceTearOff {
  const _$PushDeviceTearOff();

  _PushDevice call(
      {@JsonKey(name: 'type')
          required String type,
      @JsonKey(name: 'device_id')
          required String deviceId,
      @JsonKey(name: 'notification_token')
          required String notificationToken,
      @JsonKey(name: 'voip_notification_token')
          required String voipNotificationToken,
      @JsonKey(name: 'name')
          required String name,
      @JsonKey(name: 'data_pushes')
          required bool dataPushes,
      @JsonKey(name: 'data_badges')
          required bool dataBadges,
      @JsonKey(name: 'allowed_notifications')
          required bool allowedNotifications}) {
    return _PushDevice(
      type: type,
      deviceId: deviceId,
      notificationToken: notificationToken,
      voipNotificationToken: voipNotificationToken,
      name: name,
      dataPushes: dataPushes,
      dataBadges: dataBadges,
      allowedNotifications: allowedNotifications,
    );
  }

  PushDevice fromJson(Map<String, Object> json) {
    return PushDevice.fromJson(json);
  }
}

/// @nodoc
const $PushDevice = _$PushDeviceTearOff();

/// @nodoc
mixin _$PushDevice {
  /// Type: android, ios, web, safari.
  @JsonKey(name: 'type')
  String get type => throw _privateConstructorUsedError;

  /// Device id generated by client library.
  @JsonKey(name: 'device_id')
  String get deviceId => throw _privateConstructorUsedError;

  /// Notification token.
  @JsonKey(name: 'notification_token')
  String get notificationToken => throw _privateConstructorUsedError;

  /// Notification token for VOIP (iOS only).
  @JsonKey(name: 'voip_notification_token')
  String get voipNotificationToken => throw _privateConstructorUsedError;

  /// Readable device name.
  @JsonKey(name: 'name')
  String get name => throw _privateConstructorUsedError;

  /// Send silently data pushes that must be fully processed by app. Must be true for modern mobile clients.
  @JsonKey(name: 'data_pushes')
  bool get dataPushes => throw _privateConstructorUsedError;

  /// Send badge value as data. Experimental.
  @JsonKey(name: 'data_badges')
  bool get dataBadges => throw _privateConstructorUsedError;

  /// deprecated.
  @JsonKey(name: 'allowed_notifications')
  bool get allowedNotifications => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $PushDeviceCopyWith<PushDevice> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $PushDeviceCopyWith<$Res> {
  factory $PushDeviceCopyWith(
          PushDevice value, $Res Function(PushDevice) then) =
      _$PushDeviceCopyWithImpl<$Res>;
  $Res call(
      {@JsonKey(name: 'type') String type,
      @JsonKey(name: 'device_id') String deviceId,
      @JsonKey(name: 'notification_token') String notificationToken,
      @JsonKey(name: 'voip_notification_token') String voipNotificationToken,
      @JsonKey(name: 'name') String name,
      @JsonKey(name: 'data_pushes') bool dataPushes,
      @JsonKey(name: 'data_badges') bool dataBadges,
      @JsonKey(name: 'allowed_notifications') bool allowedNotifications});
}

/// @nodoc
class _$PushDeviceCopyWithImpl<$Res> implements $PushDeviceCopyWith<$Res> {
  _$PushDeviceCopyWithImpl(this._value, this._then);

  final PushDevice _value;
  // ignore: unused_field
  final $Res Function(PushDevice) _then;

  @override
  $Res call({
    Object? type = freezed,
    Object? deviceId = freezed,
    Object? notificationToken = freezed,
    Object? voipNotificationToken = freezed,
    Object? name = freezed,
    Object? dataPushes = freezed,
    Object? dataBadges = freezed,
    Object? allowedNotifications = freezed,
  }) {
    return _then(_value.copyWith(
      type: type == freezed
          ? _value.type
          : type // ignore: cast_nullable_to_non_nullable
              as String,
      deviceId: deviceId == freezed
          ? _value.deviceId
          : deviceId // ignore: cast_nullable_to_non_nullable
              as String,
      notificationToken: notificationToken == freezed
          ? _value.notificationToken
          : notificationToken // ignore: cast_nullable_to_non_nullable
              as String,
      voipNotificationToken: voipNotificationToken == freezed
          ? _value.voipNotificationToken
          : voipNotificationToken // ignore: cast_nullable_to_non_nullable
              as String,
      name: name == freezed
          ? _value.name
          : name // ignore: cast_nullable_to_non_nullable
              as String,
      dataPushes: dataPushes == freezed
          ? _value.dataPushes
          : dataPushes // ignore: cast_nullable_to_non_nullable
              as bool,
      dataBadges: dataBadges == freezed
          ? _value.dataBadges
          : dataBadges // ignore: cast_nullable_to_non_nullable
              as bool,
      allowedNotifications: allowedNotifications == freezed
          ? _value.allowedNotifications
          : allowedNotifications // ignore: cast_nullable_to_non_nullable
              as bool,
    ));
  }
}

/// @nodoc
abstract class _$PushDeviceCopyWith<$Res> implements $PushDeviceCopyWith<$Res> {
  factory _$PushDeviceCopyWith(
          _PushDevice value, $Res Function(_PushDevice) then) =
      __$PushDeviceCopyWithImpl<$Res>;
  @override
  $Res call(
      {@JsonKey(name: 'type') String type,
      @JsonKey(name: 'device_id') String deviceId,
      @JsonKey(name: 'notification_token') String notificationToken,
      @JsonKey(name: 'voip_notification_token') String voipNotificationToken,
      @JsonKey(name: 'name') String name,
      @JsonKey(name: 'data_pushes') bool dataPushes,
      @JsonKey(name: 'data_badges') bool dataBadges,
      @JsonKey(name: 'allowed_notifications') bool allowedNotifications});
}

/// @nodoc
class __$PushDeviceCopyWithImpl<$Res> extends _$PushDeviceCopyWithImpl<$Res>
    implements _$PushDeviceCopyWith<$Res> {
  __$PushDeviceCopyWithImpl(
      _PushDevice _value, $Res Function(_PushDevice) _then)
      : super(_value, (v) => _then(v as _PushDevice));

  @override
  _PushDevice get _value => super._value as _PushDevice;

  @override
  $Res call({
    Object? type = freezed,
    Object? deviceId = freezed,
    Object? notificationToken = freezed,
    Object? voipNotificationToken = freezed,
    Object? name = freezed,
    Object? dataPushes = freezed,
    Object? dataBadges = freezed,
    Object? allowedNotifications = freezed,
  }) {
    return _then(_PushDevice(
      type: type == freezed
          ? _value.type
          : type // ignore: cast_nullable_to_non_nullable
              as String,
      deviceId: deviceId == freezed
          ? _value.deviceId
          : deviceId // ignore: cast_nullable_to_non_nullable
              as String,
      notificationToken: notificationToken == freezed
          ? _value.notificationToken
          : notificationToken // ignore: cast_nullable_to_non_nullable
              as String,
      voipNotificationToken: voipNotificationToken == freezed
          ? _value.voipNotificationToken
          : voipNotificationToken // ignore: cast_nullable_to_non_nullable
              as String,
      name: name == freezed
          ? _value.name
          : name // ignore: cast_nullable_to_non_nullable
              as String,
      dataPushes: dataPushes == freezed
          ? _value.dataPushes
          : dataPushes // ignore: cast_nullable_to_non_nullable
              as bool,
      dataBadges: dataBadges == freezed
          ? _value.dataBadges
          : dataBadges // ignore: cast_nullable_to_non_nullable
              as bool,
      allowedNotifications: allowedNotifications == freezed
          ? _value.allowedNotifications
          : allowedNotifications // ignore: cast_nullable_to_non_nullable
              as bool,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$_PushDevice implements _PushDevice {
  const _$_PushDevice(
      {@JsonKey(name: 'type')
          required this.type,
      @JsonKey(name: 'device_id')
          required this.deviceId,
      @JsonKey(name: 'notification_token')
          required this.notificationToken,
      @JsonKey(name: 'voip_notification_token')
          required this.voipNotificationToken,
      @JsonKey(name: 'name')
          required this.name,
      @JsonKey(name: 'data_pushes')
          required this.dataPushes,
      @JsonKey(name: 'data_badges')
          required this.dataBadges,
      @JsonKey(name: 'allowed_notifications')
          required this.allowedNotifications});

  factory _$_PushDevice.fromJson(Map<String, dynamic> json) =>
      _$$_PushDeviceFromJson(json);

  @override

  /// Type: android, ios, web, safari.
  @JsonKey(name: 'type')
  final String type;
  @override

  /// Device id generated by client library.
  @JsonKey(name: 'device_id')
  final String deviceId;
  @override

  /// Notification token.
  @JsonKey(name: 'notification_token')
  final String notificationToken;
  @override

  /// Notification token for VOIP (iOS only).
  @JsonKey(name: 'voip_notification_token')
  final String voipNotificationToken;
  @override

  /// Readable device name.
  @JsonKey(name: 'name')
  final String name;
  @override

  /// Send silently data pushes that must be fully processed by app. Must be true for modern mobile clients.
  @JsonKey(name: 'data_pushes')
  final bool dataPushes;
  @override

  /// Send badge value as data. Experimental.
  @JsonKey(name: 'data_badges')
  final bool dataBadges;
  @override

  /// deprecated.
  @JsonKey(name: 'allowed_notifications')
  final bool allowedNotifications;

  @override
  String toString() {
    return 'PushDevice(type: $type, deviceId: $deviceId, notificationToken: $notificationToken, voipNotificationToken: $voipNotificationToken, name: $name, dataPushes: $dataPushes, dataBadges: $dataBadges, allowedNotifications: $allowedNotifications)';
  }

  @override
  bool operator ==(dynamic other) {
    return identical(this, other) ||
        (other is _PushDevice &&
            (identical(other.type, type) ||
                const DeepCollectionEquality().equals(other.type, type)) &&
            (identical(other.deviceId, deviceId) ||
                const DeepCollectionEquality()
                    .equals(other.deviceId, deviceId)) &&
            (identical(other.notificationToken, notificationToken) ||
                const DeepCollectionEquality()
                    .equals(other.notificationToken, notificationToken)) &&
            (identical(other.voipNotificationToken, voipNotificationToken) ||
                const DeepCollectionEquality().equals(
                    other.voipNotificationToken, voipNotificationToken)) &&
            (identical(other.name, name) ||
                const DeepCollectionEquality().equals(other.name, name)) &&
            (identical(other.dataPushes, dataPushes) ||
                const DeepCollectionEquality()
                    .equals(other.dataPushes, dataPushes)) &&
            (identical(other.dataBadges, dataBadges) ||
                const DeepCollectionEquality()
                    .equals(other.dataBadges, dataBadges)) &&
            (identical(other.allowedNotifications, allowedNotifications) ||
                const DeepCollectionEquality()
                    .equals(other.allowedNotifications, allowedNotifications)));
  }

  @override
  int get hashCode =>
      runtimeType.hashCode ^
      const DeepCollectionEquality().hash(type) ^
      const DeepCollectionEquality().hash(deviceId) ^
      const DeepCollectionEquality().hash(notificationToken) ^
      const DeepCollectionEquality().hash(voipNotificationToken) ^
      const DeepCollectionEquality().hash(name) ^
      const DeepCollectionEquality().hash(dataPushes) ^
      const DeepCollectionEquality().hash(dataBadges) ^
      const DeepCollectionEquality().hash(allowedNotifications);

  @JsonKey(ignore: true)
  @override
  _$PushDeviceCopyWith<_PushDevice> get copyWith =>
      __$PushDeviceCopyWithImpl<_PushDevice>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$_PushDeviceToJson(this);
  }
}

abstract class _PushDevice implements PushDevice {
  const factory _PushDevice(
      {@JsonKey(name: 'type')
          required String type,
      @JsonKey(name: 'device_id')
          required String deviceId,
      @JsonKey(name: 'notification_token')
          required String notificationToken,
      @JsonKey(name: 'voip_notification_token')
          required String voipNotificationToken,
      @JsonKey(name: 'name')
          required String name,
      @JsonKey(name: 'data_pushes')
          required bool dataPushes,
      @JsonKey(name: 'data_badges')
          required bool dataBadges,
      @JsonKey(name: 'allowed_notifications')
          required bool allowedNotifications}) = _$_PushDevice;

  factory _PushDevice.fromJson(Map<String, dynamic> json) =
      _$_PushDevice.fromJson;

  @override

  /// Type: android, ios, web, safari.
  @JsonKey(name: 'type')
  String get type => throw _privateConstructorUsedError;
  @override

  /// Device id generated by client library.
  @JsonKey(name: 'device_id')
  String get deviceId => throw _privateConstructorUsedError;
  @override

  /// Notification token.
  @JsonKey(name: 'notification_token')
  String get notificationToken => throw _privateConstructorUsedError;
  @override

  /// Notification token for VOIP (iOS only).
  @JsonKey(name: 'voip_notification_token')
  String get voipNotificationToken => throw _privateConstructorUsedError;
  @override

  /// Readable device name.
  @JsonKey(name: 'name')
  String get name => throw _privateConstructorUsedError;
  @override

  /// Send silently data pushes that must be fully processed by app. Must be true for modern mobile clients.
  @JsonKey(name: 'data_pushes')
  bool get dataPushes => throw _privateConstructorUsedError;
  @override

  /// Send badge value as data. Experimental.
  @JsonKey(name: 'data_badges')
  bool get dataBadges => throw _privateConstructorUsedError;
  @override

  /// deprecated.
  @JsonKey(name: 'allowed_notifications')
  bool get allowedNotifications => throw _privateConstructorUsedError;
  @override
  @JsonKey(ignore: true)
  _$PushDeviceCopyWith<_PushDevice> get copyWith =>
      throw _privateConstructorUsedError;
}
