import 'package:freezed_annotation/freezed_annotation.dart';

enum CounterpartyType { 
  @JsonValue('COUNTERPARTY_TYPE_UNSPECIFIED')
  COUNTERPARTY_TYPE_UNSPECIFIED,
  
  @JsonValue('COUNTERPARTY_TYPE_PHYSICAL')
  COUNTERPARTY_TYPE_PHYSICAL,
  
  @JsonValue('COUNTERPARTY_TYPE_SELFEMPLOYED')
  COUNTERPARTY_TYPE_SELFEMPLOYED,
  
  @JsonValue('COUNTERPARTY_TYPE_ENTREPRENEUR')
  COUNTERPARTY_TYPE_ENTREPRENEUR,
  
  @JsonValue('COUNTERPARTY_TYPE_JURIDICAL')
  COUNTERPARTY_TYPE_JURIDICAL,
  
}
