import 'package:freezed_annotation/freezed_annotation.dart';

enum EnquiryStatus { 
  @JsonValue('ENQUIRY_STATUS_UNSPECIFIED')
  ENQUIRY_STATUS_UNSPECIFIED,
  
  @JsonValue('ENQUIRY_STATUS_PAID')
  ENQUIRY_STATUS_PAID,
  
  @JsonValue('ENQUIRY_STATUS_EXPIRED')
  ENQUIRY_STATUS_EXPIRED,
  
  @JsonValue('ENQUIRY_STATUS_CANCELLED')
  ENQUIRY_STATUS_CANCELLED,
  
  @JsonValue('ENQUIRY_STATUS_WAITING_CONFIRMATION')
  ENQUIRY_STATUS_WAITING_CONFIRMATION,
  
  @JsonValue('ENQUIRY_STATUS_WAITING_CREDITING')
  ENQUIRY_STATUS_WAITING_CREDITING,
  
}
