import 'package:freezed_annotation/freezed_annotation.dart';

enum EnquiryStatusFilter { 
  @JsonValue('ENQUIRY_STATUS_FILTER_PAID')
  ENQUIRY_STATUS_FILTER_PAID,
  
  @JsonValue('ENQUIRY_STATUS_FILTER_EXPIRED')
  ENQUIRY_STATUS_FILTER_EXPIRED,
  
  @JsonValue('ENQUIRY_STATUS_FILTER_CANCELLED')
  ENQUIRY_STATUS_FILTER_CANCELLED,
  
  @JsonValue('ENQUIRY_STATUS_FILTER_WAITING_CONFIRMATION')
  ENQUIRY_STATUS_FILTER_WAITING_CONFIRMATION,
  
  @JsonValue('ENQUIRY_STATUS_FILTER_WAITING_CREDITING')
  ENQUIRY_STATUS_FILTER_WAITING_CREDITING,
  
}
