import 'package:freezed_annotation/freezed_annotation.dart';

enum EnquiryPaymentStatus { 
  @JsonValue('ENQUIRY_PAYMENT_STATUS')
  ENQUIRY_PAYMENT_STATUS,
  
  @JsonValue('ENQUIRY_PAYMENT_STATUS_WAITING_CONFIRMATION')
  ENQUIRY_PAYMENT_STATUS_WAITING_CONFIRMATION,
  
  @JsonValue('ENQUIRY_PAYMENT_STATUS_WAITING_CREDITING')
  ENQUIRY_PAYMENT_STATUS_WAITING_CREDITING,
  
  @JsonValue('ENQUIRY_PAYMENT_STATUS_PAID')
  ENQUIRY_PAYMENT_STATUS_PAID,
  
}
