import 'package:freezed_annotation/freezed_annotation.dart';

enum MeetingRepeatabilityType { 
  @JsonValue('MEETING_PRESENCE_STATUS_UNSPECIFIED')
  MEETING_PRESENCE_STATUS_UNSPECIFIED,
  
  @JsonValue('MEETING_PRESENCE_STATUS_DAILY')
  MEETING_PRESENCE_STATUS_DAILY,
  
  @JsonValue('MEETING_PRESENCE_STATUS_WEEKLY')
  MEETING_PRESENCE_STATUS_WEEKLY,
  
  @JsonValue('MEETING_PRESENCE_STATUS_MONTHLY')
  MEETING_PRESENCE_STATUS_MONTHLY,
  
  @JsonValue('MEETING_PRESENCE_STATUS_NDOW')
  MEETING_PRESENCE_STATUS_NDOW,
  
  @JsonValue('MEETING_PRESENCE_STATUS_ANNUALLY')
  MEETING_PRESENCE_STATUS_ANNUALLY,
  
}
