import 'package:freezed_annotation/freezed_annotation.dart';

enum PaymentType { 
  @JsonValue('PAYMENT_TYPE_UNSPECIFIED')
  PAYMENT_TYPE_UNSPECIFIED,
  
  @JsonValue('PAYMENT_TYPE_PAPER_DOCUMENT_MANAGEMENT')
  PAYMENT_TYPE_PAPER_DOCUMENT_MANAGEMENT,
  
  @JsonValue('PAYMENT_TYPE_ELECTRONIC_DOCUMENT_MANAGEMENT')
  PAYMENT_TYPE_ELECTRONIC_DOCUMENT_MANAGEMENT,
  
  @JsonValue('PAYMENT_TYPE_BANK_CARD')
  PAYMENT_TYPE_BANK_CARD,
  
  @JsonValue('PAYMENT_TYPE_TECHNICAL')
  PAYMENT_TYPE_TECHNICAL,
  
}
