// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'terms.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Terms _$_$_TermsFromJson(Map<String, dynamic> json) {
  return $checkedNew(r'_$_Terms', json, () {
    final val = _$_Terms(
      enInTeam: $checkedConvert(json, 'EnInTeam', (v) => v as String),
      enTeam: $checkedConvert(json, 'EnTeam', (v) => v as String),
      enTeamAccess: $checkedConvert(json, 'EnTeamAccess', (v) => v as String),
      enTeamAdmin: $checkedConvert(json, 'EnTeamAdmin', (v) => v as String),
      enTeamAdmins: $checkedConvert(json, 'EnTeamAdmins', (v) => v as String),
      enTeamGuest: $checkedConvert(json, 'EnTeamGuest', (v) => v as String),
      enTeamMember: $checkedConvert(json, 'EnTeamMember', (v) => v as String),
      enTeamMembers: $checkedConvert(json, 'EnTeamMembers', (v) => v as String),
      enTeamOwner: $checkedConvert(json, 'EnTeamOwner', (v) => v as String),
      enTeamSettings:
          $checkedConvert(json, 'EnTeamSettings', (v) => v as String),
      ruTeamSettings:
          $checkedConvert(json, 'RuTeamSettings', (v) => v as String),
      enTeams: $checkedConvert(json, 'EnTeams', (v) => v as String),
      enToTeam: $checkedConvert(json, 'EnToTeam', (v) => v as String),
      ruInTeam: $checkedConvert(json, 'RuInTeam', (v) => v as String),
      ruTeam: $checkedConvert(json, 'RuTeam', (v) => v as String),
      ruTeamAccess: $checkedConvert(json, 'RuTeamAccess', (v) => v as String),
      ruTeamAdmin: $checkedConvert(json, 'RuTeamAdmin', (v) => v as String),
      ruTeamAdmins: $checkedConvert(json, 'RuTeamAdmins', (v) => v as String),
      ruTeamD: $checkedConvert(json, 'RuTeamD', (v) => v as String),
      ruTeamGuest: $checkedConvert(json, 'RuTeamGuest', (v) => v as String),
      ruTeamMember: $checkedConvert(json, 'RuTeamMember', (v) => v as String),
      ruTeamMembers: $checkedConvert(json, 'RuTeamMembers', (v) => v as String),
      ruTeamOwner: $checkedConvert(json, 'RuTeamOwner', (v) => v as String),
      ruTeamP: $checkedConvert(json, 'RuTeamP', (v) => v as String),
      ruTeamR: $checkedConvert(json, 'RuTeamR', (v) => v as String),
      ruTeams: $checkedConvert(json, 'RuTeams', (v) => v as String),
      ruTeamsD: $checkedConvert(json, 'RuTeamsD', (v) => v as String),
      ruTeamsP: $checkedConvert(json, 'RuTeamsP', (v) => v as String),
      ruTeamsR: $checkedConvert(json, 'RuTeamsR', (v) => v as String),
      ruTeamsT: $checkedConvert(json, 'RuTeamsT', (v) => v as String),
      ruTeamsV: $checkedConvert(json, 'RuTeamsV', (v) => v as String),
      ruTeamT: $checkedConvert(json, 'RuTeamT', (v) => v as String),
      ruTeamV: $checkedConvert(json, 'RuTeamV', (v) => v as String),
      ruToTeam: $checkedConvert(json, 'RuToTeam', (v) => v as String),
    );
    return val;
  }, fieldKeyMap: const {
    'enInTeam': 'EnInTeam',
    'enTeam': 'EnTeam',
    'enTeamAccess': 'EnTeamAccess',
    'enTeamAdmin': 'EnTeamAdmin',
    'enTeamAdmins': 'EnTeamAdmins',
    'enTeamGuest': 'EnTeamGuest',
    'enTeamMember': 'EnTeamMember',
    'enTeamMembers': 'EnTeamMembers',
    'enTeamOwner': 'EnTeamOwner',
    'enTeamSettings': 'EnTeamSettings',
    'ruTeamSettings': 'RuTeamSettings',
    'enTeams': 'EnTeams',
    'enToTeam': 'EnToTeam',
    'ruInTeam': 'RuInTeam',
    'ruTeam': 'RuTeam',
    'ruTeamAccess': 'RuTeamAccess',
    'ruTeamAdmin': 'RuTeamAdmin',
    'ruTeamAdmins': 'RuTeamAdmins',
    'ruTeamD': 'RuTeamD',
    'ruTeamGuest': 'RuTeamGuest',
    'ruTeamMember': 'RuTeamMember',
    'ruTeamMembers': 'RuTeamMembers',
    'ruTeamOwner': 'RuTeamOwner',
    'ruTeamP': 'RuTeamP',
    'ruTeamR': 'RuTeamR',
    'ruTeams': 'RuTeams',
    'ruTeamsD': 'RuTeamsD',
    'ruTeamsP': 'RuTeamsP',
    'ruTeamsR': 'RuTeamsR',
    'ruTeamsT': 'RuTeamsT',
    'ruTeamsV': 'RuTeamsV',
    'ruTeamT': 'RuTeamT',
    'ruTeamV': 'RuTeamV',
    'ruToTeam': 'RuToTeam'
  });
}

Map<String, dynamic> _$_$_TermsToJson(_$_Terms instance) => <String, dynamic>{
      'EnInTeam': instance.enInTeam,
      'EnTeam': instance.enTeam,
      'EnTeamAccess': instance.enTeamAccess,
      'EnTeamAdmin': instance.enTeamAdmin,
      'EnTeamAdmins': instance.enTeamAdmins,
      'EnTeamGuest': instance.enTeamGuest,
      'EnTeamMember': instance.enTeamMember,
      'EnTeamMembers': instance.enTeamMembers,
      'EnTeamOwner': instance.enTeamOwner,
      'EnTeamSettings': instance.enTeamSettings,
      'RuTeamSettings': instance.ruTeamSettings,
      'EnTeams': instance.enTeams,
      'EnToTeam': instance.enToTeam,
      'RuInTeam': instance.ruInTeam,
      'RuTeam': instance.ruTeam,
      'RuTeamAccess': instance.ruTeamAccess,
      'RuTeamAdmin': instance.ruTeamAdmin,
      'RuTeamAdmins': instance.ruTeamAdmins,
      'RuTeamD': instance.ruTeamD,
      'RuTeamGuest': instance.ruTeamGuest,
      'RuTeamMember': instance.ruTeamMember,
      'RuTeamMembers': instance.ruTeamMembers,
      'RuTeamOwner': instance.ruTeamOwner,
      'RuTeamP': instance.ruTeamP,
      'RuTeamR': instance.ruTeamR,
      'RuTeams': instance.ruTeams,
      'RuTeamsD': instance.ruTeamsD,
      'RuTeamsP': instance.ruTeamsP,
      'RuTeamsR': instance.ruTeamsR,
      'RuTeamsT': instance.ruTeamsT,
      'RuTeamsV': instance.ruTeamsV,
      'RuTeamT': instance.ruTeamT,
      'RuTeamV': instance.ruTeamV,
      'RuToTeam': instance.ruToTeam,
    };
