// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'terms.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Terms _$$_TermsFromJson(Map<String, dynamic> json) => _$_Terms(
      enInTeam: json['EnInTeam'] as String,
      enTeam: json['EnTeam'] as String,
      enTeamAccess: json['EnTeamAccess'] as String,
      enTeamAdmin: json['EnTeamAdmin'] as String,
      enTeamAdmins: json['EnTeamAdmins'] as String,
      enTeamGuest: json['EnTeamGuest'] as String,
      enTeamMember: json['EnTeamMember'] as String,
      enTeamMembers: json['EnTeamMembers'] as String,
      enTeamOwner: json['EnTeamOwner'] as String,
      enTeamSettings: json['EnTeamSettings'] as String,
      ruTeamSettings: json['RuTeamSettings'] as String,
      enTeams: json['EnTeams'] as String,
      enToTeam: json['EnToTeam'] as String,
      ruInTeam: json['RuInTeam'] as String,
      ruTeam: json['RuTeam'] as String,
      ruTeamAccess: json['RuTeamAccess'] as String,
      ruTeamAdmin: json['RuTeamAdmin'] as String,
      ruTeamAdmins: json['RuTeamAdmins'] as String,
      ruTeamD: json['RuTeamD'] as String,
      ruTeamGuest: json['RuTeamGuest'] as String,
      ruTeamMember: json['RuTeamMember'] as String,
      ruTeamMembers: json['RuTeamMembers'] as String,
      ruTeamOwner: json['RuTeamOwner'] as String,
      ruTeamP: json['RuTeamP'] as String,
      ruTeamR: json['RuTeamR'] as String,
      ruTeams: json['RuTeams'] as String,
      ruTeamsD: json['RuTeamsD'] as String,
      ruTeamsP: json['RuTeamsP'] as String,
      ruTeamsR: json['RuTeamsR'] as String,
      ruTeamsT: json['RuTeamsT'] as String,
      ruTeamsV: json['RuTeamsV'] as String,
      ruTeamT: json['RuTeamT'] as String,
      ruTeamV: json['RuTeamV'] as String,
      ruToTeam: json['RuToTeam'] as String,
    );

Map<String, dynamic> _$$_TermsToJson(_$_Terms instance) => <String, dynamic>{
      'EnInTeam': instance.enInTeam,
      'EnTeam': instance.enTeam,
      'EnTeamAccess': instance.enTeamAccess,
      'EnTeamAdmin': instance.enTeamAdmin,
      'EnTeamAdmins': instance.enTeamAdmins,
      'EnTeamGuest': instance.enTeamGuest,
      'EnTeamMember': instance.enTeamMember,
      'EnTeamMembers': instance.enTeamMembers,
      'EnTeamOwner': instance.enTeamOwner,
      'EnTeamSettings': instance.enTeamSettings,
      'RuTeamSettings': instance.ruTeamSettings,
      'EnTeams': instance.enTeams,
      'EnToTeam': instance.enToTeam,
      'RuInTeam': instance.ruInTeam,
      'RuTeam': instance.ruTeam,
      'RuTeamAccess': instance.ruTeamAccess,
      'RuTeamAdmin': instance.ruTeamAdmin,
      'RuTeamAdmins': instance.ruTeamAdmins,
      'RuTeamD': instance.ruTeamD,
      'RuTeamGuest': instance.ruTeamGuest,
      'RuTeamMember': instance.ruTeamMember,
      'RuTeamMembers': instance.ruTeamMembers,
      'RuTeamOwner': instance.ruTeamOwner,
      'RuTeamP': instance.ruTeamP,
      'RuTeamR': instance.ruTeamR,
      'RuTeams': instance.ruTeams,
      'RuTeamsD': instance.ruTeamsD,
      'RuTeamsP': instance.ruTeamsP,
      'RuTeamsR': instance.ruTeamsR,
      'RuTeamsT': instance.ruTeamsT,
      'RuTeamsV': instance.ruTeamsV,
      'RuTeamT': instance.ruTeamT,
      'RuTeamV': instance.ruTeamV,
      'RuToTeam': instance.ruToTeam,
    };
