// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target

part of 'client_confirm_params.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#custom-getters-and-methods');

ClientConfirmParams _$ClientConfirmParamsFromJson(Map<String, dynamic> json) {
  return _ClientConfirmParams.fromJson(json);
}

/// @nodoc
mixin _$ClientConfirmParams {
  /// Unique identifier generated by client.
  @JsonKey(name: 'confirm_id')
  String get confirmId => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $ClientConfirmParamsCopyWith<ClientConfirmParams> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $ClientConfirmParamsCopyWith<$Res> {
  factory $ClientConfirmParamsCopyWith(
          ClientConfirmParams value, $Res Function(ClientConfirmParams) then) =
      _$ClientConfirmParamsCopyWithImpl<$Res, ClientConfirmParams>;
  @useResult
  $Res call({@JsonKey(name: 'confirm_id') String confirmId});
}

/// @nodoc
class _$ClientConfirmParamsCopyWithImpl<$Res, $Val extends ClientConfirmParams>
    implements $ClientConfirmParamsCopyWith<$Res> {
  _$ClientConfirmParamsCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? confirmId = null,
  }) {
    return _then(_value.copyWith(
      confirmId: null == confirmId
          ? _value.confirmId
          : confirmId // ignore: cast_nullable_to_non_nullable
              as String,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$_ClientConfirmParamsCopyWith<$Res>
    implements $ClientConfirmParamsCopyWith<$Res> {
  factory _$$_ClientConfirmParamsCopyWith(_$_ClientConfirmParams value,
          $Res Function(_$_ClientConfirmParams) then) =
      __$$_ClientConfirmParamsCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call({@JsonKey(name: 'confirm_id') String confirmId});
}

/// @nodoc
class __$$_ClientConfirmParamsCopyWithImpl<$Res>
    extends _$ClientConfirmParamsCopyWithImpl<$Res, _$_ClientConfirmParams>
    implements _$$_ClientConfirmParamsCopyWith<$Res> {
  __$$_ClientConfirmParamsCopyWithImpl(_$_ClientConfirmParams _value,
      $Res Function(_$_ClientConfirmParams) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? confirmId = null,
  }) {
    return _then(_$_ClientConfirmParams(
      confirmId: null == confirmId
          ? _value.confirmId
          : confirmId // ignore: cast_nullable_to_non_nullable
              as String,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$_ClientConfirmParams implements _ClientConfirmParams {
  const _$_ClientConfirmParams(
      {@JsonKey(name: 'confirm_id') required this.confirmId});

  factory _$_ClientConfirmParams.fromJson(Map<String, dynamic> json) =>
      _$$_ClientConfirmParamsFromJson(json);

  /// Unique identifier generated by client.
  @override
  @JsonKey(name: 'confirm_id')
  final String confirmId;

  @override
  String toString() {
    return 'ClientConfirmParams(confirmId: $confirmId)';
  }

  @override
  bool operator ==(dynamic other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$_ClientConfirmParams &&
            (identical(other.confirmId, confirmId) ||
                other.confirmId == confirmId));
  }

  @JsonKey(ignore: true)
  @override
  int get hashCode => Object.hash(runtimeType, confirmId);

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$_ClientConfirmParamsCopyWith<_$_ClientConfirmParams> get copyWith =>
      __$$_ClientConfirmParamsCopyWithImpl<_$_ClientConfirmParams>(
          this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$_ClientConfirmParamsToJson(
      this,
    );
  }
}

abstract class _ClientConfirmParams implements ClientConfirmParams {
  const factory _ClientConfirmParams(
          {@JsonKey(name: 'confirm_id') required final String confirmId}) =
      _$_ClientConfirmParams;

  factory _ClientConfirmParams.fromJson(Map<String, dynamic> json) =
      _$_ClientConfirmParams.fromJson;

  @override

  /// Unique identifier generated by client.
  @JsonKey(name: 'confirm_id')
  String get confirmId;
  @override
  @JsonKey(ignore: true)
  _$$_ClientConfirmParamsCopyWith<_$_ClientConfirmParams> get copyWith =>
      throw _privateConstructorUsedError;
}
