// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target

part of 'server_confirm_params.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#custom-getters-and-methods');

ServerConfirmParams _$ServerConfirmParamsFromJson(Map<String, dynamic> json) {
  return _ServerConfirmParams.fromJson(json);
}

/// @nodoc
mixin _$ServerConfirmParams {
  /// Unique id generated by server.
  @JsonKey(name: 'confirm_id')
  String get confirmId => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $ServerConfirmParamsCopyWith<ServerConfirmParams> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $ServerConfirmParamsCopyWith<$Res> {
  factory $ServerConfirmParamsCopyWith(
          ServerConfirmParams value, $Res Function(ServerConfirmParams) then) =
      _$ServerConfirmParamsCopyWithImpl<$Res, ServerConfirmParams>;
  @useResult
  $Res call({@JsonKey(name: 'confirm_id') String confirmId});
}

/// @nodoc
class _$ServerConfirmParamsCopyWithImpl<$Res, $Val extends ServerConfirmParams>
    implements $ServerConfirmParamsCopyWith<$Res> {
  _$ServerConfirmParamsCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? confirmId = null,
  }) {
    return _then(_value.copyWith(
      confirmId: null == confirmId
          ? _value.confirmId
          : confirmId // ignore: cast_nullable_to_non_nullable
              as String,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$_ServerConfirmParamsCopyWith<$Res>
    implements $ServerConfirmParamsCopyWith<$Res> {
  factory _$$_ServerConfirmParamsCopyWith(_$_ServerConfirmParams value,
          $Res Function(_$_ServerConfirmParams) then) =
      __$$_ServerConfirmParamsCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call({@JsonKey(name: 'confirm_id') String confirmId});
}

/// @nodoc
class __$$_ServerConfirmParamsCopyWithImpl<$Res>
    extends _$ServerConfirmParamsCopyWithImpl<$Res, _$_ServerConfirmParams>
    implements _$$_ServerConfirmParamsCopyWith<$Res> {
  __$$_ServerConfirmParamsCopyWithImpl(_$_ServerConfirmParams _value,
      $Res Function(_$_ServerConfirmParams) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? confirmId = null,
  }) {
    return _then(_$_ServerConfirmParams(
      confirmId: null == confirmId
          ? _value.confirmId
          : confirmId // ignore: cast_nullable_to_non_nullable
              as String,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$_ServerConfirmParams implements _ServerConfirmParams {
  const _$_ServerConfirmParams(
      {@JsonKey(name: 'confirm_id') required this.confirmId});

  factory _$_ServerConfirmParams.fromJson(Map<String, dynamic> json) =>
      _$$_ServerConfirmParamsFromJson(json);

  /// Unique id generated by server.
  @override
  @JsonKey(name: 'confirm_id')
  final String confirmId;

  @override
  String toString() {
    return 'ServerConfirmParams(confirmId: $confirmId)';
  }

  @override
  bool operator ==(dynamic other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$_ServerConfirmParams &&
            (identical(other.confirmId, confirmId) ||
                other.confirmId == confirmId));
  }

  @JsonKey(ignore: true)
  @override
  int get hashCode => Object.hash(runtimeType, confirmId);

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$_ServerConfirmParamsCopyWith<_$_ServerConfirmParams> get copyWith =>
      __$$_ServerConfirmParamsCopyWithImpl<_$_ServerConfirmParams>(
          this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$_ServerConfirmParamsToJson(
      this,
    );
  }
}

abstract class _ServerConfirmParams implements ServerConfirmParams {
  const factory _ServerConfirmParams(
          {@JsonKey(name: 'confirm_id') required final String confirmId}) =
      _$_ServerConfirmParams;

  factory _ServerConfirmParams.fromJson(Map<String, dynamic> json) =
      _$_ServerConfirmParams.fromJson;

  @override

  /// Unique id generated by server.
  @JsonKey(name: 'confirm_id')
  String get confirmId;
  @override
  @JsonKey(ignore: true)
  _$$_ServerConfirmParamsCopyWith<_$_ServerConfirmParams> get copyWith =>
      throw _privateConstructorUsedError;
}
